# Generated by Django 2.2.7 on 2019-12-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sex',
            field=models.CharField(default='b', max_length=1, verbose_name='Sex'),
        ),
    ]
