# Generated by Django 2.2.7 on 2019-12-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_good_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='sex',
        ),
        migrations.AddField(
            model_name='good',
            name='material',
            field=models.CharField(default='rubber', max_length=10, verbose_name='Material'),
        ),
    ]
