# Generated by Django 2.2.7 on 2019-12-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_good_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='comments',
            field=models.BooleanField(default=True, verbose_name='Comments status'),
        ),
    ]
