# Generated by Django 2.2.7 on 2019-12-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='Subscribe'),
        ),
    ]
